[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "https://api.balldontlie.io/:splat"
  status = 200
  force = true
  headers = {Authorization = "3b13604b-63be-47ce-a594-bca471752359"}